#!/bin/bash

if [ "$1" = "" ]
then
    echo "usage: $0 list ..."
    exit
fi

result=""
while [ "$1" != "" ]
do
    IFS=":| "
    for sep in $1:
    do
        if [ "$sep" = "" ]
        then
            sep="."
        fi

        case "$result" in
            $sep|$sep:*|*:$sep:*|*:$sep)
                ;; # do nothing
            "") 
                result="$sep"
                ;;
            *)
                result="$result:$sep"
                ;;
        esac
    done
    IFS=" "
    shift
done
echo $result
