#!/usr/bin/ksh

USAGE="$0 -f directory
$0 -d  directory
$0 -d -f directory

-f rename files 
-d rename directories 
"

usage ()
    {
    print -u2 "$USAGE"
    exit 1
    }

pathname ()
    {
    # function provided for the student
    print -- "${1%/*}"
    }

basename ()
    {
    # function provided for the student
    print -- "${1##*/}"
    }

find_dirs ()
    {
    # function provided for the student
    find "$1" -depth -type d -name "* *" \
    | my_rename  

    

    }

find_files ()
    {
    # function provided for the student
    find "$1" -depth -type f -name "* *" \
    | my_rename
    }
 
my_rename()
{ 

 if [ ! -w $1 ]
    then 
    echo "not writtable directory"
    exit 1
 fi


 while IFS= read -r f ; do mv -i "$f" "$(dirname "$f")/$(basename "$f"|tr ' ' -)" ; done

}

fix_dirs ()
    {
    # The student must implement this function
    # to actually call the my_rename funtion to 
    # change the name of the directory from having spaces to
    # changing all of the spaces to -'s
    # if the name were "a b", the new name would be a-b
    # if the name were "a   b" the new name would be a----b
     # remove this line when you implement the function
    find_dirs "$DIR"
 


    }

fix_files ()
    {
    # The student must implement this function
    # to actually call the my_rename funtion to 
    # change the name of the file from having spaces to
    # changing all of the spaces to -'s
    # if the name were "a b", the new name would be a-b
    # if the name were "a   b" the new name would be a----b
    # remove this line when you implement the function
    find_files "$DIR"
 
    }









WFILE=
WDIR=
DIR=

if [ "$#" -eq 0 ]
   then
   usage
   fi

while [ $# -gt 0 ] 
    do
    case $1 in
    -d)
        WDIR=1
        ;;
    -f)
        WFILE=1
        ;;
    -*)
        usage 
        ;;
    *)
	if [ -d "$1" ]
	    then
	    DIR="$1"
	else
	    print -u2 "$1 does not exist ..."
	    exit 1
	    fi
	;;
    esac
    shift
    done

# The student must implement the following:
# - if the directory was not specified, the script should 
#   print a message and exit

# - if the Directory specified is the current directory, the script 
#   print a error message and exit

# - if the directory specified is . or .. the script should print
#   an error message and exit

# - if both -f and -d are not specified, the script should print a
#   message and exit
#

dir_check(){
    if [ ! "$DIR" ]
        then 
        echo "error: Please specify a directory."
        exit 1
    elif  [ "$DIR" = "." ] || [ "$DIR" = ".." ]
        then
        echo "error: Directory name . or .. is not available."
        exit 1

    elif [ "${PWD#*$DIR}" != "$PWD" ] 
        then 
        echo "error: Directory specified is the current directory"
        exit 1
    fi
}




dir_check



if [ "$WDIR" -a "$WFILE" ]
    then
    
    fix_files "$DIR"
    fix_dirs "$DIR"


elif [ "$WDIR" ]
    then
    fix_dirs "$DIR"
elif [ "$WFILE" ]
    then
    fix_files "$DIR"
else
    echo "error: -f or -d is not specified"
    exit 1

fi

