#!/bin/bash
#vals=':mnt/var/lib/vmware/Virtual:Machines /dev /proc /sys /tmp /usr/portage /var/tmp'
#IFS=":| "
#for i in $vals

#do

#	echo $i 

#done


#!/bin/bash
#echo "Script executed from: ${PWD}"

#BASEDIR=$(dirname $0)
#echo "Script location: ${BASEDIR}

#if [ "$(grep "$1" "${PWD}")" -ge 1 ]
#	then 
#		echo "ada"
#else
#	echo "adad"
#fi

#i	echo "yeah"
#fi



if [ "${PWD#*$1}" != "$PWD" ] 
	then
      echo "ya"
else
      echo "no"
fi